name: biomedisa
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - abseil-cpp=20210324.2=h0e60522_0
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.4=py39ha55989b_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - aom=3.4.0=h0e60522_1
  - astor=0.8.1=pyh9f0ad1d_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - blas=1.0=mkl
  - blinker=1.6.2=pyhd8ed1ab_0
  - blosc=1.21.1=h74325e0_3
  - boost=1.74.0=py39hefe7e4c_5
  - boost-cpp=1.74.0=h9f4b32c_8
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - bzip2=1.0.8=h8ffe710_4
  - c-blosc2=2.3.1=hdf67494_0
  - ca-certificates=2023.01.10=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - certifi=2022.12.7=py39haa95532_0
  - cffi=1.15.1=py39h68f70e3_3
  - cfitsio=4.1.0=h5a969a9_0
  - charls=2.3.4=h39d44d4_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=win_pyhd8ed1ab_2
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - contourpy=1.0.4=py39h2e07f2f_0
  - cryptography=39.0.0=py39h58e9bdb_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - cudnn=8.2.1=cuda11.3_0
  - curl=7.83.1=h789b8ee_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py39hb82d6ee_0
  - dask-core=2023.5.0=pyhd8ed1ab_0
  - dav1d=1.0.0=h8ffe710_1
  - dipy=1.5.0=py39hb0a1f21_1
  - double-conversion=3.2.0=h0e60522_0
  - eigen=3.4.0=h2d74725_0
  - expat=2.5.0=h63175ca_1
  - ffmpeg=4.3.1=ha925a31_0
  - fftw=3.3.10=nompi_h52fa85e_103
  - flatbuffers=23.3.3=h63175ca_0
  - fonttools=4.37.1=py39hb82d6ee_0
  - freeglut=3.2.2=h0e60522_1
  - freetype=2.12.1=h546665d_0
  - frozenlist=1.3.3=py39ha55989b_0
  - fsspec=2023.5.0=pyh1a96a4e_0
  - gast=0.4.0=pyh9f0ad1d_0
  - giflib=5.2.1=h8d14728_2
  - gl2ps=1.4.2=h0597ee9_0
  - glew=2.1.0=h39d44d4_2
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.46.3=py39hb76b349_0
  - h5py=3.7.0=nompi_py39hd4deaf1_100
  - hdf4=4.2.15=h0e5069d_4
  - hdf5=1.12.1=nompi_h2a0e4a3_104
  - icc_rt=2022.1.0=h6049295_2
  - icu=68.2=h0e60522_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs=2022.7.27=py39h1c15bc2_0
  - imagecodecs-lite=2019.12.3=py39h5d4886f_5
  - imageio=2.28.1=pyh24c5eb1_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h57928b3_3556
  - itk=5.2.0=py39h832f523_0
  - jasper=2.0.33=h77af90b_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_2
  - jsoncpp=1.9.5=h2d74725_1
  - jxrlib=1.1=h8ffe710_2
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py39h2e07f2f_0
  - krb5=1.19.3=h1176d77_0
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libaec=1.0.6=h39d44d4_0
  - libavif=0.10.1=h8ffe710_1
  - libblas=3.9.0=12_win64_mkl
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libcblas=3.9.0=12_win64_mkl
  - libclang=11.1.0=default_h5c34c98_1
  - libcurl=7.83.1=h789b8ee_0
  - libdeflate=1.12=h8ffe710_0
  - libexpat=2.5.0=h63175ca_1
  - libiconv=1.17=h8ffe710_0
  - libitk=5.2.0=hac70a04_4
  - libitk-devel=5.2.0=h3bb2308_4
  - liblapack=3.9.0=12_win64_mkl
  - liblapacke=3.9.0=12_win64_mkl
  - libnetcdf=4.8.1=nompi_h1cc8e9d_102
  - libogg=1.3.4=h8ffe710_1
  - libopencv=4.5.1=py39h27d8466_0
  - libpng=1.6.37=h1d00b33_4
  - libprotobuf=3.17.2=h7755175_1
  - libssh2=1.10.0=h680486a_3
  - libtheora=1.1.1=h8d14728_1005
  - libtiff=4.4.0=h2ed3b44_1
  - libwebp-base=1.2.4=h8ffe710_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.10.1=hf5bbc77_0
  - libzip=1.9.2=hfed4ece_1
  - libzlib=1.2.12=h8ffe710_2
  - libzopfli=1.0.3=h0e60522_0
  - llvmlite=0.39.0=py39ha0cd8c8_1
  - locket=1.0.0=pyhd8ed1ab_0
  - loguru=0.7.0=py39hcbf5309_0
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.2=py39ha55989b_0
  - matplotlib=3.7.1=py39hcbf5309_0
  - matplotlib-base=3.7.1=py39hf11a4ad_1
  - medpy=0.4.0=py39h6a716af_1
  - mkl=2021.4.0=h0e2418a_729
  - mkl-service=2.4.0=py39h6b0492b_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.4=py39ha55989b_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - networkx=3.1=pyhd8ed1ab_0
  - nibabel=5.1.0=py39hcbf5309_2
  - numba=0.56.3=py39hf11a4ad_0
  - numexpr=2.7.3=py39h2e25243_2
  - numpy=1.21.5=py39h6331f09_1
  - numpy-stl=2.17.1=py39h5d4886f_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - opencv=4.5.1=py39hcbf5309_0
  - openjpeg=2.5.0=hc9384bd_1
  - openssl=1.1.1w=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=1.4.3=py39h2e25243_0
  - partd=1.4.0=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pillow=9.2.0=py39hcef8f5f_2
  - pip=23.0.1=py39haa95532_0
  - proj=9.0.0=h1cfcee9_1
  - protobuf=3.17.2=py39h415ef7b_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pugixml=1.11.4=h0e60522_0
  - py-opencv=4.5.1=py39h832f523_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydicom=2.3.1=pyh1a96a4e_0
  - pyjwt=2.7.0=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hb0d2dfa_4
  - pysocks=1.7.1=pyh0701188_6
  - pytables=3.7.0=py39hbcfe41f_0
  - python=3.9.16=h6244533_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-flatbuffers=1.12=pyhd8ed1ab_1
  - python-utils=3.5.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2023.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.3.0=py39h5d4886f_1
  - pyyaml=6.0=py39hb82d6ee_4
  - qt=5.12.9=h5909a2a_4
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-image=0.19.2=py39h2e25243_0
  - scikit-learn=1.1.2=py39hfd4428b_0
  - scipy=1.9.3=py39h321e85e_1
  - setuptools=66.0.0=py39haa95532_0
  - simpleitk=2.1.0=py39hc8d2e25_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=h82413e6_1
  - sqlite=3.41.2=h2bbff1b_0
  - statsmodels=0.13.2=py39h5d4886f_0
  - tbb=2021.5.0=h2d74725_1
  - tbb-devel=2021.5.0=h2d74725_1
  - tensorboard=2.6.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.1=py39hcbf5309_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.6.0=gpu_py39he88c5ba_0
  - tensorflow-base=2.6.0=gpu_py39hb3da07e_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - tensorflow-gpu=2.6.0=h17022bd_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2021.7.2=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py39hb82d6ee_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - typing-extensions=4.6.0=hd8ed1ab_0
  - typing_extensions=4.6.0=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=14.0.0=py39hb82d6ee_1
  - urllib3=1.26.14=py39haa95532_0
  - utfcpp=3.2.3=h57928b3_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.34.31931=h5081d32_16
  - vs2015_runtime=14.34.31931=hed1258a_16
  - vtk=9.1.0=qt_py39h1ab545e_208
  - werkzeug=2.3.4=pyhd8ed1ab_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - win32_setctime=1.1.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - wrapt=1.15.0=py39ha55989b_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - yarl=1.9.1=py39ha55989b_0
  - zfp=0.5.5=h0e60522_8
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.12=h8ffe710_2
  - zlib-ng=2.0.6=h8ffe710_0
  - zstd=1.5.2=h6255e5f_4
  - pip:
      - appdirs==1.4.4
      - itk-core==5.2.0
      - itk-filtering==5.2.0
      - itk-numerics==5.2.0
      - itk-registration==5.2.0
      - mako==1.2.4
      - mpi4py==3.1.4
      - platformdirs==3.10.0
      - pycuda==2022.2.2
      - pyopencl==2023.1.2
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - pytools==2023.1.1
